#define MIC_NO_ERROR		 0
//DXAudioOutput
#define DIRECTSOUND_OUT_CREATE_FAILED 1
#define DIRECTSOUND_OUT_SETCOOPERATIVELEVEL_FAILED 2
#define DIRECTSOUND_OUT_CREATESOUNDBUFFER_PRIMARY_FAILED 3
#define DIRECTSOUND_OUT_SETFORMAT_FAILED 4
#define DIRECTSOUND_OUT_GETFORMAT_FAILED 5
#define DIRECTSOUND_OUT_CREATESOUNDBUFFER_SECONDARY_FAILED 6
#define DIRECTSOUND_OUT_QUERYINTERFACE_NOTIFY_FAILED 7
#define DIRECTSOUND_OUT_INITIAL_LOCK_FAILED 8
#define DIRECTSOUND_OUT_INITIAL_UNLOCK_FAILED 9
#define DIRECTSOUND_OUT_PLAY_FAILED 10
#define DIRECTSOUND_OUT_LOST_DEVICE 11

//DXAudioInput

#define DIRECTSOUND_IN_CAPTURE_CREATE_FAILED 20
#define DIRECTSOUND_IN_CREATE_CAPTURE_BUFFER_FAILED 21
#define DIRECTSOUND_IN_QUERYINTERFACE_NOTIFY_FAILED 22
#define DIRECTSOUND_IN_OPEN_CHOSEN_DEVICE_FAILED 23 //not critical
#define DIRECTSOUND_IN_START_FAILED 24
#define DIRECTSOUND_IN_LOST_DEVICE 25

//WASAPIInput

#define WASAPI_IN_INSTATIATE_ENUMERATOR_FAILED 30
#define WASAPI_IN_OPEN_CHOSEN_DEVICE_FAILED 31 //not critical
#define WASAPI_IN_OPEN_DEVICE_FAILED 32
#define WASAPI_IN_QUERY_DEVICE_FAILED 33
#define WASAPI_IN_REOPEN_DEFAULT_DEVICE_FAILED 34
#define WASAPI_IN_ACTIVATE_MIC_AUDIOCLIENT_FAILED 35
#define WASAPI_IN_SUBFORMAT_IS_NOT_IEEE_FORMAT 36
#define WASAPI_IN_MIC_INITIALIZE_FAILED 37
#define WASAPI_IN_MIC_GETSERVICE_FAILED 38
#define WASAPI_IN_SET_MIC_EVENT_FAILED 39
#define WASAPI_IN_START_MIC_FAILED 40
#define WASAPI_IN_GET_NEXT_PACKET_FAILED 41

//WASAPIOutput

#define WASAPI_OUT_INSTATIATE_ENUMERATOR_FAILED 50
#define WASAPI_OUT_OPEN_CHOSEN_DEVICE_FAILED 51 //not critical
#define WASAPI_OUT_OPEN_DEVICE_FAILED 52
#define WASAPI_OUT_QUERY_DEVICE_FAILED 53
#define WASAPI_OUT_REOPEN_DEFAULT_DEVICE_FAILED 54
#define WASAPI_OUT_ACTIVATE_AUDIOCLIENT_FAILED 55
#define WASAPI_OUT_GETMIXFORMAT_FAILED 56
#define WASAPI_OUT_GETSERVICE_FAILED 57
#define WASAPI_OUT_SET_EVENT_FAILED 58
#define WASAPI_OUT_START_FAILED 59
#define WASAPI_OUT_SUBFORMAT_IS_NOT_IEEE_FORMAT 60
#define WASAPI_OUT_MIC_INITIALIZE_FAILED 61
#define WASAPI_OUT_GET_GETCURRENTPADDING_FAILED 62
#define WASAPI_OUT_GET_GETBUFFER_FAILED 63

#define IS_DSOUND_ERROR_CODE( aParam) \
	(aParam < WASAPI_IN_INSTATIATE_ENUMERATOR_FAILED ? true : false)
	