
#include "StdAfx.h"
#include "ToolsParameters.h"

#define START_PARAM_SIZE_BLOCK	int GetToolParameterSize(int paramID) { switch(paramID) {
#define END_PARAM_SIZE_BLOCK	} return 0; }
#define DEF_PARAM_SIZE(x, y)	case x: return y;

START_PARAM_SIZE_BLOCK
	DEF_PARAM_SIZE(PEN_COLOR, 4)
	DEF_PARAM_SIZE(PEN_WIDTH, 1)
	DEF_PARAM_SIZE(PEN_OPACITY, 1)
	DEF_PARAM_SIZE(CIRCLE_COLOR, 4)
	DEF_PARAM_SIZE(CIRCLE_BACK_COLOR, 4)
	DEF_PARAM_SIZE(CIRCLE_STROKE_WIDTH, 1)
	DEF_PARAM_SIZE(CIRCLE_OPACITY, 1)
	DEF_PARAM_SIZE(CIRCLE_MODE, 1)
	DEF_PARAM_SIZE(RECTANGLE_COLOR, 4)
	DEF_PARAM_SIZE(RECTANGLE_BACK_COLOR, 4)
	DEF_PARAM_SIZE(RECTANGLE_STROKE_WIDTH, 1)
	DEF_PARAM_SIZE(RECTANGLE_OPACITY, 1)
	DEF_PARAM_SIZE(RECTANGLE_MODE, 1)
	DEF_PARAM_SIZE(LINE_COLOR, 4)
	DEF_PARAM_SIZE(LINE_WIDTH, 1)
	DEF_PARAM_SIZE(LINE_OPACITY, 1)
	DEF_PARAM_SIZE(ERASER_WIDTH, 1)
	DEF_PARAM_SIZE(ERASER_OPACITY, 1)
	DEF_PARAM_SIZE(TEXT_FONT_NAME, 1)
	DEF_PARAM_SIZE(TEXT_COLOR, 4)
	DEF_PARAM_SIZE(TEXT_SIZE, 1)
	DEF_PARAM_SIZE(TEXT_BOLD, 1)
	DEF_PARAM_SIZE(TEXT_ITALIC, 1)
	DEF_PARAM_SIZE(TEXT_UNDERLINE, 1)
	DEF_PARAM_SIZE(TEXT_ANTIALIASING, 1)
	DEF_PARAM_SIZE(TEXT_OPACITY, 1)
	DEF_PARAM_SIZE(CLEAR_COLOR, 4)
	DEF_PARAM_SIZE(SELECTION_COLOR, 4)
	DEF_PARAM_SIZE(LINE_ARROW1, 1)
	DEF_PARAM_SIZE(LINE_ARROW2, 1)
	DEF_PARAM_SIZE(LINE_ARROW_LENGTH, 4)
	DEF_PARAM_SIZE(TEXT_NEW_CURSOR_POSITION, 1)
END_PARAM_SIZE_BLOCK