
#pragma once

#define FRAME_BLOCK_CHECK_MAP_MESSAGES	0
#define FRAME_BLOCK_BEGIN_FRAME			1
#define FRAME_BLOCK_CONTROLLERS_UPDATE	2
#define FRAME_BLOCK_RENDER_SCENE		3
#define FRAME_BLOCK_RMML_UPDATE			4
#define FRAME_BLOCK_END_FRAME			5
#define FRAME_BLOCK_RESLOADER_UPDATE	6
#define FRAME_BLOCK_SOUNDMAN_UPDATE		7
