#define WM_WS3D_MOUSEMOVE     WM_USER +  WM_MOUSEMOVE
#define WM_WS3D_LBUTTONDOWN   WM_USER +  WM_LBUTTONDOWN
#define WM_WS3D_LBUTTONUP     WM_USER +  WM_LBUTTONUP
#define WM_WS3D_LBUTTONDBLCLK WM_USER +  WM_LBUTTONDBLCLK
#define WM_WS3D_RBUTTONDOWN   WM_USER +  WM_RBUTTONDOWN
#define WM_WS3D_RBUTTONUP     WM_USER +  WM_RBUTTONUP
#define WM_WS3D_RBUTTONDBLCLK WM_USER +  WM_RBUTTONDBLCLK
#define WM_WS3D_MBUTTONDOWN   WM_USER +  WM_MBUTTONDOWN
#define WM_WS3D_MBUTTONUP     WM_USER +  WM_MBUTTONUP
#define WM_WS3D_MBUTTONDBLCLK WM_USER +  WM_MBUTTONDBLCLK

#define WM_WS3D_KEYDOWN WM_USER + WM_KEYDOWN
#define WM_WS3D_KEYUP   WM_USER + WM_KEYUP
