//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfoMan.rc
//
#define IDD_SETTINGS                    9
#define IDD_SETTINGS2                   9
#define IDD_SCRIPTTESTTAB               101
#define IDD_SHARINGTAB                  102
#define IDD_DIALOG1                     103
#define IDD_NET_SESSIONS                104
#define IDD_RECORDTAB                   105
#define IDD_RESOURCELOAD                117
#define IDB_IMAP                        121
#define IDD_ABOUTBOX                    500
#define IDD_OBJECT_COORDINATE_PROP      501
#define IDD_OBJECT_SYNC_PROP            502
#define IDD_LOGVIEW                     503
#define IDD_SCRIPT_EXECUTE              504
#define IDR_MAINFRAME                   528
#define IDR_MAINFRAME_OLD               529
#define IDD_BASEDIALOG                  530
#define IDC_VIEW_AREA                   531
#define IDD_OBJECTVIEW                  532
#define IDC_TREE_OBJECT                 1000
#define IDC_TREE_TEST                   1001
#define IDC_SLIDER_QUALITY              1002
#define IDC_TEST_RESULT                 1003
#define IDC_STATIC_QUALITY              1004
#define IDC_EDIT_FIND                   1005
#define IDC_BUTTON_STOP                 1006
#define IDC_STATIC_FINDER_TOOL          1007
#define IDC_BUTTON_FIND                 1008
#define IDC_HANDLE_EDIT                 1009
#define IDC_NAME_EDIT                   1010
#define IDC_STATIC_FIND                 1011
#define IDC_BUTTON_SELECT               1012
#define IDC_STATIC_FILTER               1013
#define IDC_LIST3                       1014
#define IDC_BUTTON3                     1015
#define IDC_LIST1                       1016
#define IDC_LIST_RECORD2                1017
#define IDC_BUTTON_DESELECT             1018
#define IDC_LIST2                       1019
#define IDC_SIZE_STATIC                 1020
#define IDC_UPDATE_BINSTATE             1021
#define IDC_CHECK_FILTER                1022
#define IDC_EMULATE_NETWORK_BREAKS      1022
#define IDC_BUTTON_OPEN_SRC             1023
#define IDC_CHECK_SYNCH                 1024
#define IDC_IMAGE_BOX                   1025
#define IDC_BREAK_OBJECT_SERVER_CONNECTION 1025
#define IDC_TREE_SHARING_SETTINGS       1026
#define IDC_BREAK_OBJECT_SERVER_CONNECTION2 1026
#define IDC_BREAK_RES_SERVER_CONNECTION 1026
#define IDC_EDIT1                       1027
#define IDC_BREAK_VOIP_SERVER_CONNECTION 1027
#define IDC_EDIT_OUTPUT                 1028
#define IDC_BREAK_SERVICE_SERVER_CONNECTION2 1028
#define IDC_BREAK_SERVICE_SERVER_CONNECTION 1028
#define IDC_HIDE_CHECK                  1029
#define IDC_EDIT_SRC                    1030
#define IDC_SESSION_VIEW                1031
#define IDC_BUTTON_UPDATE               1032
#define IDC_BUTTON2                     1033
#define IDC_EDIT_ID                     1034
#define IDC_SOCKET_SESSION_VIEW         1035
#define IDC_STATIC_ID                   1036
#define IDC_BUTTON_UPDATE_SESSIONS      1037
#define IDC_STATIC_SRC                  1038
#define IDC_SCROLLBAR1                  1039
#define IDC_CHECK_CHARACTER             1040
#define IDC_CHECK_CLASSES               1041
#define IDC_CHECK_AUTOUPDATE            1042
#define IDC_GROUP_FILTERS               1043
#define IDC_CHECK_RENDER_MAN            1044
#define IDC_CHECK_SOUND_MAN             1045
#define IDC_CHECK_COM_MAN               1046
#define IDC_CHECK_AVATAR_EDITOR         1047
#define IDC_CHECK_SOME_LOG_TYPE1        1048
#define IDC_EDIT_LOG_USER_TYPE1         1049
#define IDC_EDIT_LOG_USER_TYPE2         1050
#define IDC_CHECK_SOME_LOG_TYPE2        1051
#define IDC_EDIT_LOG_USER_TYPE3         1052
#define IDC_CHECK_SOME_LOG_TYPE3        1053
#define IDC_CHECK_DEFAULT               1054
#define IDC_RICH_EDIT_LOG               1055
#define IDC_RICHEDIT_LOG                1056
#define IDC_SCROLLBAR2                  1057
#define IDC_EDIT_PROP                   1058
#define IDC_TAB1                        1059
#define IDC_STATIC_X                    1060
#define IDC_STATIC_Y                    1061
#define IDC_STATIC_Z                    1062
#define IDC_EDIT_COORD_X                1063
#define IDC_EDIT_COORD_Y                1064
#define IDC_EDIT3                       1065
#define IDC_EDIT_COORD_Z                1066
#define IDC_TREE_RECORD_SETTINGS        1067
#define IDC_RECORD_VIEW                 1068
#define IDC_BUTTON_RL                   1069
#define IDC_BUTTON_RI                   1070
#define IDC_BUTTON_EX                   1071
#define IDC_BUTTON_IM                   1072
#define IDC_LIST_RECORD                 1073
#define IDC_EDIT_SCRIPT                 1074
#define IDC_BUTTON_EXECUTE              1075
#define IDC_CHECK_INFO_MAN              1076
#define IDC_CHECK_MDUMP                 1077
#define IDC_CHECK_NTEXTURE              1078
#define IDC_CHECK_OMSPLAYER             1079
#define IDC_CHECK_PATH_REFINER          1080
#define IDC_CHECK_RESLOADER             1081
#define IDC_CHECK_RMML                  1082
#define IDC_CHECK_SERVICE_MAN           1083
#define IDC_CHECK_SYNC_MAN              1084
#define IDC_CHECK_VASENCODER            1085
#define IDC_CHECK_VIDEO                 1086
#define IDC_CHECK_VOIP_MAN              1087
#define IDC_CHECK_NPHYSICS              1088
#define IDC_BUTTON1                     1089
#define IDC_PROP_UPDATE_BUTTON          1090
#define IDC_BUTTON_START                1091
#define IDC_PROP_UPDATE_BUTTON2         1092
#define IDC_STATIC_PROPERTIES           1093
#define IDC_EDIT_PROPERTIES             1094
#define IDC_SHOW_HIDDEN_3DO             1095
#define IDC_TREE_SOCKETS                1096
#define IDC_RESOURCE_CHECK              1097
#define IDC_BUTTON_COMPINFO_TO_BUFFER   1098
#define IDC_BUTTON_GETLIST              1099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
