
#pragma once

#define PHYSICS_OBJECT_TYPE_NONE					0
#define PHYSICS_OBJECT_TYPE_BOX						1
#define PHYSICS_OBJECT_TYPE_SPHERE					2
#define PHYSICS_OBJECT_TYPE_CYLINDER				3
#define PHYSICS_OBJECT_TYPE_STATIC_PLANE			4	
#define PHYSICS_OBJECT_TYPE_STATIC_BOX				5
#define PHYSICS_OBJECT_TYPE_STATIC_SPHERE			6
#define PHYSICS_OBJECT_TYPE_STATIC_CYLINDER			7
#define PHYSICS_OBJECT_TYPE_STATIC_TRIMESH			8
#define PHYSICS_OBJECT_TYPE_STATIC_COLLISION_MESH	9