
#pragma once

#define CMD_IDLE					1
#define CMD_INITVOIPSYSTEM			2
#define CMD_SETVOICEGAINLEVEL		3
#define CMD_TRANSMISSIONSTATE		4
#define CMD_GETMYUSERID				5
#define CMD_SETVOICEACTIVATIONLEVEL 6
#define CMD_SETAUTOGANECONTROL		7
#define CMD_SETDENOISING			8
#define CMD_GETDEVICES				9
//#define CMD_GETINPUTDEVICES			10
#define CMD_SETUSERGAINLEVEL		10
#define CMD_CONNECTTOEVOIP			11
#define CMD_JOINCHANNEL				12
#define CMD_DISCONNECTEVOIP			13
#define CMD_DOLOGIN					14
//#define CMD_GETUSER					15
#define CMD_SETUSERVOLUME			16
#define CMD_SETMASTERVOLUME			17
#define CMD_SETECHOCANCELLATION		18
#define CMD_DEVICE_ERROR_CODE		19
#define CMD_SETMIXERECHOCANCELLATION	20
#define CMD_STARTFINDMICDEVICE		21
#define CMD_ENDFINDMIVDEVICE		22

#define CMD_CONNECTIONSTATUS		31
#define CMD_CHANNELJOINED			32
#define CMD_CHANNELLEFT				33
#define CMD_USERTALKINGSTATUS		34
#define CMD_KICKED					35
#define CMD_ADDUSER					36
#define CMD_REMOVEUSER				37
#define CMD_CURRENTINPUTLEVEL		38
#define CMD_GETINPUTDEVICES			39
#define CMD_LOG						40
#define CMD_GETOUTPUTDEVICES		41
#define CMD_CLOSEVOIPMANSERVER		44
#define CMD_AUTOFINDEDMIC			45
#define CMD_CONFIRMATION			100