//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cal3d_max_exporter_max7.rc
//
#define IDS_SKELETON_EXPORT_DESCRIPTION 1
#define IDS_NULL                        2
#define IDS_ANIMATION_EXPORT_DESCRIPTION 3
#define IDS_ANIMATION_EXPORT_DESCRIPTION_2 4
#define IDS_ANIMATION_EXPORT_DESCRIPTION_3 5
#define IDS_MESH_EXPORT_DESCRIPTION     6
#define IDS_MESH_EXPORT_DESCRIPTION2    7
#define IDS_MESH_EXPORT_DESCRIPTION3    8
#define IDS_MATERIAL_EXPORT_DESCRIPTION 9
#define IDS_MATERIAL_EXPORT_DESCRIPTION2 10
#define IDS_MESH_EXPORT_DESCRIPTION4    11
#define IDS_MESH_EXPORT_DESCRIPTION5    12
#define IDS_AUTOEXPORT_MESHES           13
#define IDD_FLARES                      106
#define IDD_SKELETON_HIERARCHY_PAGE     107
#define IDC_HIERARCHY                   3001
#define IDI_TYPE_BONE                   3002
#define IDC_URL                         3003
#define IDB_CAL3D_LOGO                  3004
#define IDI_TYPE_DUMMY                  3005
#define IDD_ABOUT                       3006
#define IDI_TYPE_OTHER                  3007
#define IDD_SKELETON_FILE_PAGE          3008
#define IDD_ANIMATION_TIME_PAGE         3009
#define IDD_BONE_ASSIGNMENT_PAGE        3010
#define IDD_LOD_PAGE                    3011
#define IDD_MATERIAL_SELECTION_PAGE     3012
#define IDD_MATERIAL_MAPS_PAGE          3013
#define IDD_SPRINGSYSTEM_PAGE           3014
#define IDR_CAL3D_MAX_EXPORTER          4000
#define IDC_LRU                         4001
#define IDB_CAL3D_BAR                   4002
#define IDC_FACEEX                      4002
#define IDC_BROWSE                      4003
#define IDC_BROWSEF                     4004
#define IDD_MATERIALPROPSDLG            4005
#define IDC_EXPCONFIGFILE               4006
#define IDD_LIGHTS                      4007
#define IDC_STEP                        4008
#define IDD_DIALOG1                     4009
#define IDC_DESCRIPTION                 4010
#define IDC_START_FRAME                 4011
#define IDC_BROWSEECF                   4012
#define IDC_END_FRAME                   4013
#define IDC_WEIGHT_THRESHOLD            4014
#define IDC_EXPCONFIGNAME               4015
#define IDC_DISPLACEMENT                4016
#define IDC_MAX_BONE_COUNT              4017
#define IDC_BROWSETEXT                  4018
#define IDC_VALUE_EXACT                 4018
#define IDC_POS_COMPARE_VALUE_EXACT     4018
#define IDC_FPS                         4019
#define IDC_MATERIAL                    4020
#define IDC_ZPOSITION                   4021
#define IDC_MAPS                        4022
#define IDC_ENABLE_LOD                  4023
#define IDC_ENABLE_SPRINGSYSTEM         4024
#define IDC_ENABLE_FLIP                 4025
#define IDC_BUTTON1                     4026
#define IDC_SAVECONFIG                  4027
#define IDC_BUTTON5                     4027
#define IDC_SAVEECF                     4028
#define IDC_RELANIM                     4029
#define IDC_BUTTON2                     4030
#define IDC_SAVECONFIG2                 4031
#define IDC_SHADOWDATA                  4032
#define IDC_SAVEFIRST                   4033
#define IDC_STATICECF                   4034
#define IDC_BUTTON3                     4035
#define IDC_LOCALCOORDINATES            4036
#define IDC_SAVELAST                    4037
#define IDC_STATICCONF                  4038
#define IDC_BUTTON4                     4039
#define IDC_NORMALIZEWEIGHTS            4040
#define IDC_COMMON                      4041
#define IDC_TEXTPATH                    4042
#define IDC_STAY_ATLAST                 4043
#define IDC_STATIC2                     4044
#define IDC_WALKANIMATION               4045
#define IDC_MTRLPATH                    4046
#define IDC_MATERIALS                   4047
#define IDC_OPTIMIZEANIMATIONS          4048
#define IDC_CHECKAMB                    4049
#define IDC_CHECKDIF                    4050
#define IDC_KEEPCFG                     4051
#define IDC_LIST1                       4052
#define IDC_SEPCOMMONOBJECTS            4052
#define IDC_GETMTRLSNAMES               4053
#define IDC_EDIT1                       4054
#define IDC_SEPCOMMONTEXTURES           4054
#define IDC_EDIT2                       4055
#define IDC_USELODS                     4055
#define IDC_EDIT3                       4056
#define IDC_USEPREFIXES                 4056
#define IDC_EDIT4                       4057
#define IDC_GENSQL                      4057
#define IDSet                           4058
#define IDC_GENSQL2                     4058
#define IDC_GENDBID                     4058
#define IDC_USETEXTURESPATH             4059
#define IDC_USEMATERIALSPATH            4060
#define IDC_RESNAME                     4061
#define IDC_GENGLOBALCOORDS             4061
#define IDC_HIDEWND                     4062
#define IDC_EXPALL                      4063
#define IDD_AUTOEXPORTUTILITY           4064
#define IDD_AUDOEXPORTSETTINGSDIALOG    4065
#define IDC_CHECK_USE_LEFT_ASSIGMENT2RIGHT 4066
#define IDC_CHECK_USE_RIGHT_ASSIGMENT2LEFT 4067
#define IDC_RADIO_USE_LEFT_ASSIGMENT2RIGHT 4068
#define IDC_RADIO_USE_RIGHT_ASSIGMENT2LEFT 4069
#define IDC_RADIO_NO_SIDE_ASSIGMENT     4070
#define IDC_DOAUTOEXPORT                4071
#define IDC_WELD                        4072
#define IDC_AUTOEXPORTSETTINGS          4073
#define IDC_PARSERURL                   4074
#define IDC_DOAUTOEXPORT2               4074
#define IDC_LIBEXPORT                   4074
#define IDC_GEOMETRYPATH                4075
#define IDC_MODULENAME                  4076
#define IDC_WORLDX                      4079
#define IDC_WORLDY                      4080
#define IDC_AUTOEXPORT                  4082
#define IDC_QUALITY_SLIDER              4085
#define IDC_USEFLOATVERTEX              4086
#define IDC_AUTOHPOLY                   4087
#define IDC_SERVER77					4089
#define IDC_SERVER78					4090
#define IDC_SERVER_OTHER				4091
#define IDC_GROUP						4092
#define IDC_KEEPRTNSINANIMATION         4093
#define IDC_AUTOGEOMETRYONLY			4094
#define IDC_AUTOWITHOUTTEXTURES			4095
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4077
#define _APS_NEXT_COMMAND_VALUE         4077
#define _APS_NEXT_CONTROL_VALUE         4088
#define _APS_NEXT_SYMED_VALUE           4079
#endif
#endif
