
#pragma once

#define USER_DATA_NRMOBJECT					0
#define USER_DATA_LEVEL						1
#define USER_DATA_TYPE						1
#define USER_DATA_LOD						2
#define USER_DATA_SRC						3
#define USER_DATA_WAS_COLLISION				4
#define USER_DATA_RENDER_TARGET				5
#define USER_DATA_SHARING_TARGET			6
#define USER_DATA_OBJECT_IN_LECTURE_GROUP	7
#define USER_DATA_EDITABLE					8
#define USER_DATA_IS_LOCATION				9
#define USER_DATA_IS_COMMUNICATION_AREA		10
#define USER_DATA_SPRITE					9

#define LEVEL_BOX_COLLISION					0
#define LEVEL_GROUND						1
#define LEVEL_NO_COLLISION					2
#define LEVEL_SEA							3
#define LEVEL_CAMERA_COLLISION_TOO			4
#define LEVEL_CAMERA_COLLISION_ONLY			5
#define LEVEL_SPHERE_COLLISION				6
#define LEVEL_COLLISION_MESH				7